import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import tournamentsRouter from "./tournaments.js";
import leaderboardRouter from "./leaderboard.js";
import historyRouter from "./history.js";
import adminRouter from "./admin.js";
import storageRouter from "./storage.js";
import freefireRouter from "./freefire.js";
import walletRouter from "./wallet.js";
import notificationsRouter from "./notifications.js";
import squadsRouter from "./squads.js";
import superAdminRouter from "./super-admin.js";
import topupRouter from "./topup.js";
import supportRouter from "./support.js";
import reportsRouter from "./reports.js";
import pushRouter from "./push.js";
import securityAdminRouter from "./security-admin.js";
import fraudMonitorRouter from "./fraud-monitor.js";
import bannerUploadRouter from "./banner-upload.js";
import avatarUploadRouter from "./avatar-upload.js";
import tournamentUploadRouter from "./tournament-upload.js";
import slotMatchesRouter from "./slot-matches.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(tournamentsRouter);
router.use(leaderboardRouter);
router.use(historyRouter);
router.use(adminRouter);
router.use(storageRouter);
router.use(freefireRouter);
router.use(walletRouter);
router.use(notificationsRouter);
router.use(squadsRouter);
router.use(superAdminRouter);
router.use(topupRouter);
router.use(supportRouter);
router.use(reportsRouter);
router.use(pushRouter);
router.use(securityAdminRouter);
router.use(fraudMonitorRouter);
router.use(bannerUploadRouter);
router.use(avatarUploadRouter);
router.use(tournamentUploadRouter);
router.use(slotMatchesRouter);

export default router;
